// Mocks generated by Mockito 5.4.6 from annotations
// in eduvest_output/test/features/home/helpers/home_test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:eduvest_output/features/home/domain/entities/goal_summary_entity.dart'
    as _i5;
import 'package:eduvest_output/features/home/domain/entities/transaction_entity.dart'
    as _i4;
import 'package:eduvest_output/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i2.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<double> getTotalBalance() => (super.noSuchMethod(
        Invocation.method(
          #getTotalBalance,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<({double limit, double spent})> getMonthlyBudget() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyBudget,
          [],
        ),
        returnValue: _i3.Future<({double limit, double spent})>.value(
            (limit: 0.0, spent: 0.0)),
      ) as _i3.Future<({double limit, double spent})>);

  @override
  _i3.Future<List<_i4.TransactionEntity>> getRecentTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentTransactions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TransactionEntity>>.value(
            <_i4.TransactionEntity>[]),
      ) as _i3.Future<List<_i4.TransactionEntity>>);

  @override
  _i3.Future<_i5.GoalSummaryEntity?> getActiveGoal() => (super.noSuchMethod(
        Invocation.method(
          #getActiveGoal,
          [],
        ),
        returnValue: _i3.Future<_i5.GoalSummaryEntity?>.value(),
      ) as _i3.Future<_i5.GoalSummaryEntity?>);

  @override
  _i3.Future<double> getBalanceChangePercent() => (super.noSuchMethod(
        Invocation.method(
          #getBalanceChangePercent,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Stream<List<_i4.TransactionEntity>> watchRecentTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecentTransactions,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.TransactionEntity>>.empty(),
      ) as _i3.Stream<List<_i4.TransactionEntity>>);
}
