// Mocks generated by Mockito 5.4.6 from annotations
// in eduvest_output/test/features/expense/helpers/expense_test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:eduvest_output/core/errors/failures.dart' as _i6;
import 'package:eduvest_output/features/expense/domain/entities/expense_entity.dart'
    as _i5;
import 'package:eduvest_output/features/expense/domain/repositories/expense_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i3.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.ExpenseEntity>> getExpensesStream(
    String? uid, {
    int? month,
    int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpensesStream,
          [uid],
          {
            #month: month,
            #year: year,
          },
        ),
        returnValue: _i4.Stream<List<_i5.ExpenseEntity>>.empty(),
      ) as _i4.Stream<List<_i5.ExpenseEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> addExpense(
    String? uid,
    _i5.ExpenseEntity? expense,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpense,
          [
            uid,
            expense,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #addExpense,
            [
              uid,
              expense,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> updateExpense(
    String? uid,
    _i5.ExpenseEntity? expense,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [
            uid,
            expense,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #updateExpense,
            [
              uid,
              expense,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteExpense(
    String? uid,
    String? expenseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [
            uid,
            expenseId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteExpense,
            [
              uid,
              expenseId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteReceipt(
    String? uid,
    String? expenseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReceipt,
          [
            uid,
            expenseId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteReceipt,
            [
              uid,
              expenseId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String>> uploadReceipt(
    String? uid,
    String? expenseId,
    _i7.File? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadReceipt,
          [
            uid,
            expenseId,
            file,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #uploadReceipt,
            [
              uid,
              expenseId,
              file,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, String>>);
}
