// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL3wHyLhqZgkbwYDlXj2NRPDego7K8oVQ',
    appId: '1:636538524620:web:0dcb83bfc7acaba2fc8369',
    messagingSenderId: '636538524620',
    projectId: 'educest1',
    authDomain: 'educest1.firebaseapp.com',
    storageBucket: 'educest1.firebasestorage.app',
    measurementId: 'G-CG9EF23R3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACBzgvC_pR43_PhEPfkw8Sx_Nryt3pwpE',
    appId: '1:636538524620:android:d3c8770f3be9b864fc8369',
    messagingSenderId: '636538524620',
    projectId: 'educest1',
    storageBucket: 'educest1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmW_KNr9qi-xIbKvuaJJjBPJeYFh1m7E',
    appId: '1:636538524620:ios:213abdf0ed11c210fc8369',
    messagingSenderId: '636538524620',
    projectId: 'educest1',
    storageBucket: 'educest1.firebasestorage.app',
    iosBundleId: 'com.eduvest.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkmW_KNr9qi-xIbKvuaJJjBPJeYFh1m7E',
    appId: '1:636538524620:ios:213abdf0ed11c210fc8369',
    messagingSenderId: '636538524620',
    projectId: 'educest1',
    storageBucket: 'educest1.firebasestorage.app',
    iosBundleId: 'com.eduvest.app',
  );
}
