// Mocks generated by Mockito 5.4.6 from annotations
// in eduvest_output/test/features/goals/helpers/goals_test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:eduvest_output/core/errors/failures.dart' as _i6;
import 'package:eduvest_output/features/goals/domain/entities/contribution_entity.dart'
    as _i7;
import 'package:eduvest_output/features/goals/domain/entities/goal_entity.dart'
    as _i5;
import 'package:eduvest_output/features/goals/domain/repositories/goals_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GoalsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsRepository extends _i1.Mock implements _i3.GoalsRepository {
  MockGoalsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.GoalEntity>> watchGoals(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchGoals,
          [uid],
        ),
        returnValue: _i4.Stream<List<_i5.GoalEntity>>.empty(),
      ) as _i4.Stream<List<_i5.GoalEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> createGoal(
    String? uid,
    _i5.GoalEntity? goal,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGoal,
          [
            uid,
            goal,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #createGoal,
            [
              uid,
              goal,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> addFunds(
    String? uid,
    String? goalId,
    double? amount,
    String? note,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFunds,
          [
            uid,
            goalId,
            amount,
            note,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #addFunds,
            [
              uid,
              goalId,
              amount,
              note,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> adjustPlan(
    String? uid,
    String? goalId, {
    double? targetAmount,
    DateTime? targetDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustPlan,
          [
            uid,
            goalId,
          ],
          {
            #targetAmount: targetAmount,
            #targetDate: targetDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #adjustPlan,
            [
              uid,
              goalId,
            ],
            {
              #targetAmount: targetAmount,
              #targetDate: targetDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteGoal(
    String? uid,
    String? goalId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGoal,
          [
            uid,
            goalId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteGoal,
            [
              uid,
              goalId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<List<_i7.ContributionEntity>> getRecentContributions(
    String? uid,
    String? goalId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentContributions,
          [
            uid,
            goalId,
          ],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i7.ContributionEntity>>.value(
            <_i7.ContributionEntity>[]),
      ) as _i4.Future<List<_i7.ContributionEntity>>);
}
